"""update user model for phone login

Revision ID: 7155ed293e9f
Revises: fa5cf8714c38
Create Date: 2026-01-08 05:49:12.296308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7155ed293e9f'
down_revision = 'fa5cf8714c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('identity', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_user_phone', ['phone'])
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # 核心修改：指定要删除的约束名称
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_phone', type_='unique')
        
        batch_op.drop_column('identity')
        batch_op.drop_column('gender')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
